// Code generated by protoc-gen-twirp_metrics v0.0.1, DO NOT EDIT.
// source: printerfacts.proto

package printerfacts

import "context"
import "github.com/Xe/ln"

// PrinterfactsLogging is a middleware for Printerfacts that logs all usage of the methods
type PrinterfactsLogging struct {
	next Printerfacts
}

func NewPrinterfactsLogging(next Printerfacts) Printerfacts {
	var result PrinterfactsLogging
	result.next = next
	return result
}

func (i PrinterfactsLogging) Fact(ctx context.Context, input *FactParams) (result *Facts, err error) {
	ctx = ln.WithF(ctx, ln.F{
		"twirp_package": "us.xeserv.api",
		"twirp_service": "Printerfacts",
		"twirp_method": "Fact",
	})
	ctx = ln.WithF(ctx, input.F())
	result, err = i.next.Fact(ctx, input)
	if err != nil {
		ln.Error(ctx, err)
	}
	return
}

// F ields for logging.
func (i FactParams) F() ln.F {
	return ln.F{
		"fact_params_count": i.Count,
	}
}

// F ields for logging.
func (i Facts) F() ln.F {
	return ln.F{
		"facts_facts": i.Facts,
	}
}


